### ISSUE TITLE
Rainmeter

### ISSUE THREAD

**Issue by scolex71** [meilon/DenonCMD#4]
I am trying to figure out how to use this with Rainmeter but I am new to both Rainmeter and any sort of programming. All I have accomplished is compiling the DenonCMD.exe. 
A few questions:
Where should I place the exe? (Windows 10 64bit)
Rainmeter skin published anywhere?
Do I enter the AVR ip address in the exe code somewhere or is that coded in the Rain' skin?
Sorry for the noob questions and thank you for you work.

**Comment by meilon** [comment]
This is the Rainmeter Skin I use: [AVR Small Remote.txt](https://github.com/meilon/DenonCMD/files/4136161/AVR.Small.Remote.txt)

**Comment by scolex71** [comment]
What model Denon AVR are you using? 
I ask because I am wondering if the commands are different and would like to look up your model.
In the Program.cs they don't match the commands in the control protocol docs I have for my receiver (Marantz SR6013 2018 model). 
Denon and Marantz use the exact same API but there are several versions.
Mine uses: 
PWON for Power On
MVUP for Master Volume Up
SIDVD for Switch Input DVD

**Comment by meilon** [comment]
The app was written vor an AVR-2113

**Comment by visormail** [comment]
Hi! Thank you for this program. I use it to switch on or off my Denon 4311 from a rainmeter skin. I see it can change the input to other devices too, not only tuner what's in the readme. For example DenonCMD.exe ipaddress inputDVD command is working fine. Is there a possibility to change the mode to direct?

**Comment by scolex71** [comment]
visormail

Not my program but I use one based on this. Assuming by "direct" you mean Direct sound mode try using MSDIRECT.
Do you have a copy of the IP Protocol commands list?
If no it is available at the link below.
https://www.heimkinoraum.de/upload/files/product/IP_Protocol_AVR-Xx100.pdf

**Comment by visormail** [comment]
Hello. Thank for the answer. Do you mean:
DenonCMD.exe 192.168.1.101 MSDIRECT
It isn't woking.

-------- Eredeti levél --------

Feladó: scolex71 ***@***.***>
Dátum: 2021 szeptember 6 04:38:17
Tárgy: Re: [meilon/DenonCMD] Rainmeter (#4)
Címzett: meilon/DenonCMD ***@***.***>
 
 

visormail

Not my program but I use one based on this. Assuming by "direct" you mean Direct sound mode try using MSDIRECT.
Do you have a copy of the IP Protocol commands list?
If no it is available at the link below.
https://www.heimkinoraum.de/upload/files/product/IP_Protocol_AVR-Xx100.pdf

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by meilon** [comment]
Sorry, right now my code doesn't support changing sound modes. From what I can gather from my AVR is that I can set the mode to the four main modes "movie", "music", "game" and "pure" and the four manual modes "direct", "stereo", "standard" and "simulation". All eight use the same API endpoint, therefore I think the app will not be as good as what the IR remote could do. But if thats enough for you I might add that.

If so, please open a new issue, don't hijack another issue I forgot to close because I expected an answer

**Comment by meilon** [comment]
I couldn't help myself and added this minor change in https://github.com/meilon/DenonCMD/commit/e4724943a9a342bc9c58becb2cf5e2da0c59fb46

**Comment by visormail** [comment]
Thank you. I have compiled it without errors or warnings, but these new (modeDirect, etc) functions aren't working on my receiver.

-------- Eredeti levél --------

Feladó: Christian Arnold ***@***.***>
Dátum: 2021 szeptember 7 22:50:54
Tárgy: Re: [meilon/DenonCMD] Rainmeter (#4)
Címzett: meilon/DenonCMD ***@***.***>
 
 

I couldn't help myself and added this minor change in e472494

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by meilon** [comment]
Then I'm sorry, AVR-4311 must need a different way to change this via the web API. It works with my AVR-2113.
